### ISSUE TITLE
Can't install using package control

### ISSUE THREAD

**Issue by sollymay** [yusdacra/FlutterEnhancements#3]
Hey @yusdacra, I am trying to install this on MacOS, which is POSIX compliant.

The package is not showing in package control when searched since I think its tagged for Linux only:

![Screen Shot 2020-07-06 at 11 46 58 PM](https://user-images.githubusercontent.com/6496698/86704533-fc9ec880-bfe2-11ea-9c63-4ff65b80985d.png)

Could you tag it also for MacOS? it should work no problem in theory.

**Comment by 90-008** [comment]
This should be done now https://github.com/wbond/package_control_channel/pull/8842
